bin/buddydrive usr/bin
bin/buddydrive-gui usr/bin
debian/buddydrive.conf usr/lib/tmpfiles.d
buddydrive.desktop usr/share/applications
icons/hicolor/48x48/apps/buddydrive.png usr/share/icons/hicolor/48x48/apps
icons/hicolor/128x128/apps/buddydrive.png usr/share/icons/hicolor/128x128/apps
icons/hicolor/256x256/apps/buddydrive.png usr/share/icons/hicolor/256x256/apps
icons/hicolor/512x512/apps/buddydrive.png usr/share/icons/hicolor/512x512/apps
